# Use postgres/example user/password credentials
name: pg_Express_GRP

services:

  postgres:
    image: postgres:18
    container_name: postgres-db
    restart: always
    volumes:
      - pg_express_data:/var/lib/postgresql
      # - ./data/pg_express_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: drizzle-db1

  adminer:
    image: adminer
    container_name: adminer-dbClient
    restart: always
    ports:
      - 8082:8080

volumes:
  pg_express_data:


