# Use postgres/example user/password credentials

services:

  postgres:
    image: postgres
    container_name: postgres-db2
    restart: always
    volumes:
      - pg_express_data:/var/lib/postgresq1/data
      # - ./data/pg_express_data:/var/lib/postgresq1/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: drizzle-db1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  pg_express_data:
